
platform: linux
container_limits: { }
image_resource:
  type: registry-image
  source:
    repository: maven
    tag: 3.6.3
caches:
  - path: $HOME/.m2/repository
inputs:
  - name: github-test
outputs:
  - name: image
    path: github-test
run:
  path: /bin/sh
  args:
    - -c
    - |
      mvn -f github-test/pom.xml clean install