platform: linux
container_limits: { } #IDK what this does
image_resource:
  type: registry-image
  source:
    repository: maven
    tag: 3.6.3
caches:
  - path: $HOME/.m2/repository #We will provide an input called 'src' to this Task
inputs:
  - name: github-test
outputs:
  - name: build #What do we want this task to do? Tell Concourse the commands it should execute in this Task
run:
  path: 'bash'
  args:
    - -c
    - |
      java -jar github-test/target/test-0.0.1.jar
