---
applications:
  - name: smoke-test
    memory: 1G
    instances: 1
    routes:
      - route: "((host)).((domain))"
    path: ../target/test-0.0.1.jar
    buildpack: java_buildpack
    env:
      JBP_CONFIG_OPEN_JDK_JRE: "{ jre: { version: 11.+ } }"
      IAS_XSUAA_XCHANGE_ENABLED: true
    services:
      - "((service-postgresql-name))"